apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: desafio-backstageio-v2
  title: Template do desafio Backstage.io V2
  description: Template para a criação de um novo repositório no Azure Devops.
spec:
  owner: Mariano-SI
  type: service
  parameters:
    - title: Fill in the basic information about the new project
      required:
        - projectName
        - serviceName
      properties:
        projectName:
          title: Name of project
          type: string
          description: Unique name of the project
          ui:autofocus: true
          ui:options:
            rows: 5
        serviceName:
          title: Name of service
          type: string
          description: Add a name to the new service
          ui:options:
            rows: 5
    - title: Fill the informations about the new repository
      required:
        - repoName
      properties:
        repoName:
          title: Name of the repository
          type: string
          description: Unique name of the project
          ui:options:
            rows: 5 
  steps:
    - id: publish-azure
      name: Publish to Azure DevOps
      action: publish:azure
      input:
        repoUrl: dev.azure.com?repo=${{ parameters.repoName }}&organization=marianobackstageorg&project=Backstage
        description: This is ${{ parameters.projectName }}
        defaultBranch: master

    - id: create-folder-and-push
      name: Create Folder
      action: azure:create-folder-and-push
      input:
        folderName: Config 
        organization: marianobackstageorg
        project: Backstage
        repository: ${{ parameters.repoName }}
        previousCommitHash: ${{ steps['publish-azure'].output.commitHash }}
        branchName: master

    - id: create-file-and-push
      name: Create file
      action: azure:create-file-and-push
      input:
        filePath: Config/
        fileName: config.json
        organization: marianobackstageorg
        project: Backstage
        repository: ${{ parameters.repoName }}
        branchName: master
        previousCommitHash: ${{ steps['create-folder-and-push'].output.commitId }}
        fileContent: |
          {
            "projeto": "${{ parameters.projectName }}",
            "serviço": "${{ parameters.serviceName }}"
          }

    
    - id: create-custom-branches
      name: Create Custom Branches
      action: azure-repos:branches:create
      input:
        branchNames: ["develop", "qa", "uat"]
        organization: marianobackstageorg
        project: Backstage
        repository: ${{ parameters.repoName }}
  output:
    links:
      - title: "Link do repositório"
        url: ${{ steps['publish-azure'].output.remoteUrl }}
