apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-release-pipeline
  title: Create release pipeline 
  description: Create a release pipeline for a service
  tags: 
    - pipeline
    - azure-devops
    - service
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Pipeline Configuration
      required:
        - pipelineName
      properties:
        pipelineName:
          title: Pipeline Name
          description: The name of the pipeline to create
          type: string
  steps:
    - id: create-release-pipeline
      name: Create release pipeline
      action: azure-devops:release-pipeline:create
      input:
        organization: marianobackstageorg
        project: Backstage
        repository: testeaovivo
        mainBranch: master
        pipelineName: ${{ parameters.pipelineName }}
        sourcePipelineId: 1
