apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: synchronize-azure-devops-pipelines
  title: Synchronize Azure DevOps Pipelines
  description: Synchronizes two Azure DevOps pipelines by cloning all stages and actions from one to the other
  tags: 
    - pipeline
    - azure-devops
    - service
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Pipelines Configuration
      required:
        - sourcePipeline
        - targetPipeline
      properties:
        sourcePipeline:
          title: Source Pipeline 
          description: This is the pipeline that will be used as a basis for synchronization
          type: object
          ui:field: AzureDevopsReleasePipelinesSelect
        targetPipeline:
          title: Target Pipeline 
          description: This is the pipeline that will be the target of synchronization
          type: object
          ui:field: AzureDevopsReleasePipelinesSelect
  steps:
    - id: synchronize-azure-devops-pipelines
      name: Synchronize Azure DevOps Pipelines
      action: azure-devops:release-pipeline:synchronize
      input:
        organization: marianobackstageorg
        project: Backstage
        sourcePipelineId: ${{ parameters.sourcePipeline.id }}
        targetPipelineId: ${{ parameters.targetPipeline.id }}
